### ISSUE TITLE
Request: Preset recalling

### ISSUE THREAD

**Issue by Deanbau** [bitfocus/companion-module-novastar-controller#10]
Is it possible to recall presets via this module for the VX4S

**Comment by michiel820** [comment]
I have made a number of traces with Wireshark to find out what TCP commands are used to choice presets on my VX4S. This commands work for me.

[VX4S TCP command Preset select.pdf](https://github.com/bitfocus/companion-module-novastar-controller/files/5415875/VX4S.TCP.command.Preset.select.pdf)

**Comment by josephdadams** [comment]
Just submitted a pull request that includes support for these preset values.
