### ISSUE TITLE
Novastar - NovaPro UHD Jr

### ISSUE THREAD

**Issue by PureSVG** [bitfocus/companion-module-novastar-controller#14]

**Comment by PureSVG** [comment]
No, there's support for another model that is called "NovaPro HD" (different hardware)

**Comment by josephdadams** [comment]
@PureSVG https://github.com/bitfocus/companion-module-novastar-controller/blob/0efb9cfc858ab0d117f67e554ba51821f95225f9/index.js#L203

It says NovaPro UHD Jr. What version of Companion are you running?

**Comment by PureSVG** [comment]
Oh, I see.
I didn't find it at the support page of the website. (https://bitfocus.io/support)
I thought that you didn't have support for it yet.

**Comment by josephdadams** [comment]
That page only shows modules available in the last public release, and I'm guessing this was added after that. Go download a beta and try it out!

**Comment by JeffreyDavidsz** [comment]
close due no response
