### ISSUE TITLE
Novastar UHD Jr. 

### ISSUE THREAD

**Issue by c29media** [bitfocus/companion-module-novastar-controller#15]
No response from this module. IP is correct. Mainly need preset recall.

**Comment by marklneumann** [comment]
I second this issue.  I have 2 NovaPro  UHD Jr boxes hooked up and showing a  good connection but the functions do not trigger any commands.

**Comment by bpbpoo** [comment]
same. looking for PIP on/off and/or Preset Recall. I can tell companion is connected as it pulls the preset list - when its not connected it just shows "0". The commands, however, are not being received by and/or executed by the UHD Jr

**Comment by marklneumann** [comment]
@benwillcox Thanks! I will try this out tomorrow when I get into our studio.  If you have the ability to capture the commands for the other 6 presets, that would be awesome!

**Comment by benwillcox** [comment]
OK here's the complete list:

Preset 1 - %55%aa%00%35%fe%00%00%00%00%00%01%00%00%01%51%13%01%00%00%ef%56
Preset 2 - %55%aa%00%2f%fe%00%00%00%00%00%01%00%00%01%51%13%01%00%01%ea%56
Preset 3 - %55%aa%00%30%fe%00%00%00%00%00%01%00%00%01%51%13%01%00%02%ec%56
Preset 4 - %55%aa%00%2e%fe%00%00%00%00%00%01%00%00%01%51%13%01%00%03%eb%56
Preset 5 - %55%aa%00%48%fe%00%00%00%00%00%01%00%00%01%51%13%01%00%04%06%57
Preset 6 - %55%aa%00%4d%fe%00%00%00%00%00%01%00%00%01%51%13%01%00%05%0c%57
Preset 7 - %55%aa%00%49%fe%00%00%00%00%00%01%00%00%01%51%13%01%00%06%09%57
Preset 8 - %55%aa%00%46%fe%00%00%00%00%00%01%00%00%01%51%13%01%00%07%07%57
Preset 9 - %55%aa%00%4d%fe%00%00%00%00%00%01%00%00%01%51%13%01%00%08%0f%57
Preset 10 - %55%aa%00%4c%fe%00%00%00%00%00%01%00%00%01%51%13%01%00%09%0f%57

**Comment by JeffreyDavidsz** [comment]
added this in  e8a8793ed49b7ccb9d6123bd3c19749833e2ef53 please test (wait for build 5900)
