### ISSUE TITLE
Connection Limitation?

### ISSUE THREAD

**Issue by wrldtvlr** [bitfocus/companion-module-novastar-controller#20]
Using this module to control a pair of Novastar VX4S processors and ran into an interesting limitation. From a single Stream Deck, everything works fine. However, we'd like to be able to control the Novastars from both a tech booth and production room. That doesn't seem to work. Does the Novastar work like the ATEMs? That is, limit the number of connections it accepts?

**Comment by cyberblaststudios** [comment]
Closing, as it seems as if these NovaStar processors will only support one control connection at a time.
