### ISSUE TITLE
Novastar J6 Companion Module Preset Recall not working

### ISSUE THREAD

**Issue by Brucesaz** [bitfocus/companion-module-novastar-controller#23]
Hi, we are trying to use Companion to change Preset recall on the J6 with the latest firmware. We are running it in Splicer mode and have set the J6 and it switches when using Vcan. When you run companion it sees the J6 and allows mode switch and blackout but not Preset Recall. We have tried different machines same problem. Any thoughts. When you send the cue from Companion the front screen seems to lock like its receiving a message but not the right one. Any thoughts ideas would be greatly appreciated.

**Comment by seanr2k2** [comment]
I'm also experiencing the same issue. Using UHD Jr. brightness action works, but recall presets does not work

**Comment by JeffreyDavidsz** [comment]
I've updated the module to support 32 presets for J6. My guess is that this will work for you also. Please wait for build 5900 before you download and test
