### ISSUE TITLE
VX1000 Input Selection

### ISSUE THREAD

**Issue by wrldtvlr** [bitfocus/companion-module-novastar-controller#25]
We've recently changed from two VX4Ses to a single VX1000. The Novastar module worked great for the VX4ses. I created a new connection for the VX1000 and recreated the buttons, but I'm not seeing the VX1000 respond to input source commands. The connection shows as green. The VX1000 just doesn't change sources. Any suggestions on troubleshooting?

**Comment by wrldtvlr** [comment]
Played around a little more. Even the commands that are implemented for the VX1000 aren't working right. Test pattern is only putting the screen into a partial pattern and it isn't possible to get out of it without cycling power to the VX1000. If anyone has a VX1000 API document, that would be really helpful. I've sent a request to Novastar. Will see if they respond.

**Comment by cyberblaststudios** [comment]
Currently working on a pull request to address implementing support for PIP layers for the VX1000

**Comment by cyberblaststudios** [comment]
> Currently working on a pull request to address implementing support for PIP layers for the VX1000

Here is the pull request to address this: https://github.com/bitfocus/companion-module-novastar-controller/pull/29
