### ISSUE TITLE
MCTRL4K limited actions available

### ISSUE THREAD

**Issue by lhdevt** [bitfocus/companion-module-novastar-controller#31]
Only Test Patterns and Display Mode can be changed. Latest version of Companion is installed. MCTRL4K is selected correctly.

![novastar](https://user-images.githubusercontent.com/126912066/222809557-87091461-419d-4cdd-b07a-8ec2f0f64071.jpg)

**Comment by TimothyFsr** [comment]
We're using lots of novastar products. And using companion on most of our productions. I've tested the connection with the controllers 6 months ago, but when using test patterns it only showed the patern on part of the screen.. which is strange as i never saw this problem before with setting the test patern via novaLct or via the display itself. Any idea if someone else used to have this problem as well and if/or it's fixed?

**Comment by kman1898** [comment]
Having the same issue. Not sure what happened to brightness button

**Comment by istnv** [comment]
Availble/fixed in PR #44
