### ISSUE TITLE
Module request: NovaStar J6

### ISSUE THREAD

**Issue by Rahulhasmail** [bitfocus/companion-module-novastar-controller#36]
**Layout/Preset Switching**
it is the combination of 6 Windows/Layes,
each one carries different input/size and resolution and aspect ratio

**this equipment has software control works on(windows & mac)

**software has easy user interface

**Comment by JeffreyDavidsz** [comment]
I've changed the preset list in 4e7f413e6591cca7be682f7263de951114176999 please test (wait for build 5900)

**Comment by Rahulhasmail** [comment]
Thank you I will check and revert back to you
