### ISSUE TITLE
Limited functions for VX4S on fresh installations

### ISSUE THREAD

**Issue by RGMediatec** [bitfocus/companion-module-novastar-controller#42]
Hello,

i found a weird issue within this module when doing a fresh install on multiple M1 Macbooks (also recently saw the problem one one Windows machine and one Companion-Pi):
When i first install the latest Companion on my Mac (Version: 3.0.0+6049-stable-126f27e8) and add a connection to a Novastar VX4S Controller i can only select "Change Display Mode" "Change Test Pattern" "Change Working Mode" "Recall Preset".
I now have to install the latest 2.4 (2.4.2+4911-v2-4.2-fcb5a863) Version and then reinstall the 3.0 version to get all the function supported like brightness control.

On the Companion-Pi the issue wasn't that easy to fix via update. I recently got it showing up all the supported functions doing multiple installs of different versions but i can't say for sure which combination worked here.
After i got it working i was doing a configuration reset via the "Import / Export" tab and the available functions changed back to the four ones i mentioned before.

I hope this can easily be fixed.
Please let me know if you need further informations

**Comment by RGMediatec** [comment]
I just found out that disabling and enabling the connection also works to get all the supported functions

**Comment by istnv** [comment]
The cause of this issue has been corrected.
