### ISSUE TITLE
[Request] Single Percent Brightness Control for Novastar

### ISSUE THREAD

**Issue by sebastienbaedis** [bitfocus/companion-module-novastar-controller#46]
Hello,

I have a setup with a LED WALL controlled by a Novastar VX600 where I need to adapt the brightness depending on the event and set it to either 3% or 10%. The controller is not easy to access in this installation so I wanted to do it trough Companion, but I can only increment by steps of 10%. Could this be changed to allow brightness controll on a single digit level?

Thank you in advance

**Comment by istnv** [comment]
@sebastienbaedis Are you able to test a custom module? 
I think I have a way to allow brightness adjustments in 0.5% increments but I do not have access to any controllers this week.

**Comment by sebastienbaedis** [comment]
Hello,

Yes I am! That would be perfect.
What do I have to do?

Thank you
Von meinem iPhone gesendet

Am 16.11.2023 um 06:13 schrieb John Knight Jr ***@***.***>:

﻿

@sebastienbaedis<https://github.com/sebastienbaedis> Are you able to test a custom module?
I think I have a way to allow brightness adjustments in 0.5% increments but I do not have access to any controllers this week.

**Comment by istnv** [comment]
@sebastienbaedis You need to be running at least the latest stable (v3.1.2) companion.
What operating system are you using? (Mac, Windows, Linux, Pi)

**Comment by sebastienbaedis** [comment]
I‘m running Companion on Windows and the 3.2.0 latest beta.


Von meinem iPhone gesendet

Am 16.11.2023 um 18:24 schrieb John Knight Jr ***@***.***>:

﻿

@sebastienbaedis<https://github.com/sebastienbaedis> You need to be running at least the latest stable (v3.1.2) companion.
What operating system are you using? (Mac, Windows, Linux, Pi)

**Comment by istnv** [comment]
I've added a new command. Should be in the next beta build
`Set Brightness` that lets you enter the percentage you want.

**Comment by sebastienbaedis** [comment]
Hello,

I’ve just donwloaded the latest beat and can confirm it works!
Thank you so much!


Sebastien Baedis

***@***.***
+352 661 152 020

3, rue de Martelange
L-8833 Wolwelange
Luxembourg

Am 17.11.2023 um 06:06 schrieb John Knight Jr ***@***.***>:



I've added a new command. Should be in the next beta build
Set Brightness that lets you enter the percentage you want.
