### ISSUE TITLE
NovaPro UHD (4k All-in-One Controller) [Module Request]

### ISSUE THREAD

**Issue by Hamid-tech** [bitfocus/companion-module-novastar-controller#5]
Hello. You can add a new NovaPro UHD module to control it with the StreamDeck remote? Make loading presets, inputs, adjusting the brightness up and down, and other functions of NovaPro Uhd.

![image](https://user-images.githubusercontent.com/66721692/84245969-f1a56500-ab16-11ea-9ee8-413c004c1366.png)

**Comment by rit3sh7** [comment]
@Hamid-tech VX6 module is same exact for this unit. it already exists and i have tested it on Nova Pro UHD Jr, u dont have  NovaPro UHD to test but as far as i know its same exact commands as VX6s so try that module and let me know if you see something not working.
